# Generated by Django 5.0.4 on 2024-07-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_alter_ordencompra_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='detalles_pedido',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='precio_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
