# Generated by Django 5.0.4 on 2024-07-23 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_ordencompra_detalles_pedido_ordencompra_precio_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordencompra',
            name='metodo_entrega',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
