# Generated by Django 5.0.4 on 2024-06-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_ingrediente_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productoingrediente',
            name='ingrediente',
        ),
        migrations.AddField(
            model_name='productoingrediente',
            name='ingrediente',
            field=models.ManyToManyField(to='producto.ingrediente'),
        ),
    ]
