# Generated by Django 5.0.4 on 2024-06-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_remove_productoingrediente_ingrediente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ingrediente',
            field=models.ManyToManyField(blank=True, to='producto.ingrediente'),
        ),
    ]
