# Generated by Django 5.0.4 on 2024-07-01 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0004_producto_ingrediente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='ingrediente',
        ),
        migrations.AlterField(
            model_name='productoingrediente',
            name='ingrediente',
            field=models.ManyToManyField(blank=True, to='producto.ingrediente'),
        ),
        migrations.AlterField(
            model_name='productoingrediente',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='producto.producto'),
        ),
    ]
